# Generated by Django 4.2.4 on 2023-09-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
